//! OH Cards — 88-card projective psychological image deck.
//!
//! ## What are OH Cards?
//!
//! OH Cards (also written *Oh* cards or *OH-Karten*) were created in 1981 by
//! Ely Raman (Moritz Egetmeyer) and the Canadian artist Joseph Schlichter.
//! They were published by the Canadian game company **OH Publishing** and are
//! distributed internationally by **Moritz Egetmeyer / Eos Games**.
//!
//! **This is not a Tarot deck.**  OH Cards belong to the tradition of
//! **projective image-based psychological tools** rather than cartomancy.
//! They are placed within this module for organisational convenience, but
//! they carry no angelic, Kabbalistic, or divinatory framework — their power
//! lies entirely in free psychological projection.
//!
//! ## Structure
//!
//! The deck consists of **two separate 44-card packs** that are used together:
//!
//! | Pack         | Contents                                     | Count |
//! |--------------|----------------------------------------------|-------|
//! | **Image cards** | Evocative scenes, faces, landscapes, objects | 44    |
//! | **Word cards**  | Single words or short phrases                | 44    |
//!
//! In a reading, one Image card and one Word card are drawn together.  The
//! resulting **image + word combination** forms an associative prompt that the
//! reader explores entirely through their own free association — there is no
//! fixed correct meaning.  The same pair means something different to every
//! person and in every session.
//!
//! Total combined deck: **88 cards** (44 images + 44 words).
//!
//! ## Reading philosophy
//!
//! OH Cards are used in:
//! - Individual therapeutic or coaching sessions
//! - Group workshops and team-building
//! - Creative writing and artistic exploration
//! - Couples and family communication
//! - Spiritual reflection without a specific tradition
//!
//! The facilitator (or solo user) draws a random image + word pair and then
//! sits with questions such as:
//! - "What is happening in this image?"
//! - "How does the word connect to the image for me?"
//! - "Where do I see this pattern in my own life?"
//! - "What feeling arises?"
//! - "What does this tell me about my situation?"
//!
//! No interpretation is provided by the deck; all meaning is generated by
//! the reader's own psyche.
//!
//! ## This implementation
//!
//! Because OH Cards are a **proprietary published product** (©1981 Ely Raman
//! and Joseph Schlichter; published by Eos Games), this module does **not**
//! reproduce the actual card imagery or the exact word list from the
//! commercial deck.  Instead, it provides:
//!
//! 1. A faithful description of each **Image card's scene or subject**
//!    (as an open-ended scene prompt rather than a copy of the artwork).
//! 2. An **archetypal word** for each Word card drawn from the tradition of
//!    projective psychology and depth psychology (Jung, Perls, Assagioli),
//!    thematically aligned with the spirit of the OH system without
//!    reproducing copyrighted content.
//!
//! Users who own the physical deck should use this module as a digital
//! companion; users who do not should consider purchasing the original.
//!
//! ## Sources
//!
//! - **Egetmeyer, M.**, *OH: A Game of Discovery* (1981; Eos Games) —
//!   the original deck and accompanying booklet.
//! - **Bradway, K. & McCoard, B.**, *Sandplay: Silent Workshop of the Psyche*
//!   (1997, Routledge) — projective image work in therapeutic context.
//! - **Jung, C. G.**, *Psychological Types* (1921; CW6, Princeton UP 1971) —
//!   the archetypal images underlying free association.
//! - **Assagioli, R.**, *Psychosynthesis* (1965; Viking Press) —
//!   the use of guided imagery and symbol in personal transformation.

// ─── Data types ───────────────────────────────────────────────────────────────

/// One of the 44 OH image cards.
///
/// Image cards carry no fixed interpretation.  The `scene` field is a
/// neutral description that serves as a projective prompt.  The
/// `themes` field names the broad psychological areas the image tends
/// to evoke, without prescribing meaning.
pub struct OhImageCard {
    /// Card number within the image pack (1–44).
    pub number: u8,
    /// A scene description that functions as a projective prompt.
    pub scene: &'static str,
    /// Broad psychological or experiential themes commonly evoked.
    pub themes: &'static str,
}

/// One of the 44 OH word cards.
///
/// Word cards are single words or very short phrases.  In use they are
/// placed *face-down* beside an image card and turned over once the image
/// has been explored — adding a second associative layer.
pub struct OhWordCard {
    /// Card number within the word pack (1–44).
    pub number: u8,
    /// The word or brief phrase on the card.
    pub word: &'static str,
    /// Psychological dimension the word opens up (non-prescriptive).
    pub dimension: &'static str,
}

// ─── Image cards (1–44) ───────────────────────────────────────────────────────

pub static OH_IMAGES: &[OhImageCard] = &[
    OhImageCard { number:  1, scene: "A solitary figure stands at the edge of a vast ocean at twilight, looking toward the horizon", themes: "Longing · solitude · possibility · the unknown" },
    OhImageCard { number:  2, scene: "Two hands reaching toward each other across a space, almost but not quite touching", themes: "Connection · separation · desire · threshold" },
    OhImageCard { number:  3, scene: "A child sits alone in a large empty room, playing with a small object", themes: "Childhood · solitude · inner world · play" },
    OhImageCard { number:  4, scene: "A figure looks into a still pool; their reflection looks back differently than expected", themes: "Self-image · shadow · mirror · identity" },
    OhImageCard { number:  5, scene: "An old tree with deep roots stands in a field after a storm; broken branches lie around it", themes: "Resilience · loss · rootedness · aftermath" },
    OhImageCard { number:  6, scene: "A door stands slightly open in a long corridor; light spills through the crack", themes: "Opportunity · hesitation · secrecy · invitation" },
    OhImageCard { number:  7, scene: "A group of people at a table; one person sits slightly apart, watching", themes: "Belonging · exclusion · observation · community" },
    OhImageCard { number:  8, scene: "Someone packs a bag in the middle of the night by lamplight", themes: "Departure · secrecy · readiness · escape" },
    OhImageCard { number:  9, scene: "An embrace between two people, one's eyes are open, one's are closed", themes: "Love · vulnerability · trust · surrender" },
    OhImageCard { number: 10, scene: "A bird in a cage with the cage door open; the bird does not leave", themes: "Freedom · fear · habit · chosen confinement" },
    OhImageCard { number: 11, scene: "Hands work clay on a potter's wheel, a shape emerging from formless matter", themes: "Creation · mastery · shaping · potential" },
    OhImageCard { number: 12, scene: "A person reads a letter alone; their expression is unreadable", themes: "Communication · news · private feeling · interpretation" },
    OhImageCard { number: 13, scene: "Two figures walk away from each other on diverging paths through fog", themes: "Separation · divergence · endings · uncertainty" },
    OhImageCard { number: 14, scene: "A table set for a meal; the guests have not yet arrived or have already gone", themes: "Anticipation · absence · hospitality · waiting" },
    OhImageCard { number: 15, scene: "Someone climbs a steep hillside; the summit is not visible from where they are", themes: "Effort · perseverance · the unknown destination · challenge" },
    OhImageCard { number: 16, scene: "A window broken from the inside; glass lies outward on the sill", themes: "Rupture · breaking free · anger · release" },
    OhImageCard { number: 17, scene: "A person holds a gift with both hands; their expression is complex", themes: "Receiving · ambivalence · gratitude · expectation" },
    OhImageCard { number: 18, scene: "Someone sleeps curled up in an unusual place, not a bed", themes: "Retreat · exhaustion · vulnerability · safety found unexpectedly" },
    OhImageCard { number: 19, scene: "A market scene, crowded; in the middle a figure stands completely still", themes: "Overwhelm · stillness · dissociation · the inner amid the outer" },
    OhImageCard { number: 20, scene: "A garden overgrown and untended; something blooms regardless", themes: "Neglect · wildness · resilience · natural persistence" },
    OhImageCard { number: 21, scene: "Two children run in opposite directions, laughing", themes: "Joy · playfulness · divergence · abandon" },
    OhImageCard { number: 22, scene: "A figure kneels, head bowed, before something not visible to the viewer", themes: "Reverence · submission · prayer · the sacred" },
    OhImageCard { number: 23, scene: "An empty chair at a desk strewn with unfinished work", themes: "Absence · incompletion · interrupted life · work" },
    OhImageCard { number: 24, scene: "Someone stands in the rain without an umbrella, face tilted up", themes: "Acceptance · surrender · cleansing · choice to receive" },
    OhImageCard { number: 25, scene: "A flame in a lantern flickers; a hand is cupped around it to shield it", themes: "Protection · fragility · care · keeping alive what matters" },
    OhImageCard { number: 26, scene: "A figure at a crossroads at night, map in hand, unsure of direction", themes: "Decision · uncertainty · guidance sought · the unknown path" },
    OhImageCard { number: 27, scene: "Hands extended, offering something small and luminous", themes: "Giving · vulnerability of generosity · what we offer the world" },
    OhImageCard { number: 28, scene: "A person laughs alone at something only they can see", themes: "Private joy · inner life · imagination · unexplained delight" },
    OhImageCard { number: 29, scene: "Two people sit facing each other across a small space; neither speaks", themes: "Silence between two people · tension · intimacy · impasse" },
    OhImageCard { number: 30, scene: "A figure stands at a high window looking down at the world below", themes: "Distance · perspective · longing to descend · observation" },
    OhImageCard { number: 31, scene: "A mask lies discarded on the floor; a face is turned away from the viewer", themes: "Authenticity · performance · identity · the revealed self" },
    OhImageCard { number: 32, scene: "A boat moored alone in still water at dawn", themes: "Readiness · peaceful potential · solitude · the journey not yet begun" },
    OhImageCard { number: 33, scene: "An elder's hands rest on a younger person's shoulders", themes: "Transmission · guidance · lineage · blessing" },
    OhImageCard { number: 34, scene: "A figure digs in the earth, finding something unexpected below the surface", themes: "Discovery · excavation · the past beneath the present · excavation of self" },
    OhImageCard { number: 35, scene: "A crowd moves in one direction; one person stands and watches them pass", themes: "Individuation · resistance · the choice not to follow · witness" },
    OhImageCard { number: 36, scene: "Someone writes by candlelight in the middle of the night", themes: "Creativity · urgency · the private act of making · testimony" },
    OhImageCard { number: 37, scene: "A bridge over a wide river; someone has stopped halfway across", themes: "Transition · hesitation · the point of no return · between two worlds" },
    OhImageCard { number: 38, scene: "Two figures build something together using their hands; they disagree on how to proceed", themes: "Collaboration · conflict in creation · negotiation · shared vision" },
    OhImageCard { number: 39, scene: "An animal and a human look at each other with equal curiosity", themes: "The wild within · instinct · the non-human · unexpected kinship" },
    OhImageCard { number: 40, scene: "A person holds their own face in their hands, expression unclear", themes: "Self-regard · overwhelm · tenderness toward oneself · containment" },
    OhImageCard { number: 41, scene: "A room full of objects that belonged to someone who is no longer present", themes: "Grief · memory · what remains · the material traces of a life" },
    OhImageCard { number: 42, scene: "Someone is learning something new, clearly struggling; a small smile breaks through", themes: "Beginner's mind · learning · the joy in difficulty · becoming" },
    OhImageCard { number: 43, scene: "A light shines at the end of a long dark corridor", themes: "Hope · the approaching end of difficulty · direction in darkness" },
    OhImageCard { number: 44, scene: "A person dances alone in an open field under a wide sky", themes: "Freedom · joy · self-expression without audience · embodiment" },
];

// ─── Word cards (1–44) ────────────────────────────────────────────────────────

pub static OH_WORDS: &[OhWordCard] = &[
    OhWordCard { number:  1, word: "Longing",       dimension: "The ache toward what is absent or not yet reached" },
    OhWordCard { number:  2, word: "Trust",          dimension: "The choice to believe without guarantee" },
    OhWordCard { number:  3, word: "Silence",        dimension: "What exists in the space between words" },
    OhWordCard { number:  4, word: "Home",           dimension: "The place or feeling of true belonging" },
    OhWordCard { number:  5, word: "Fear",           dimension: "The anticipated threat that may or may not be real" },
    OhWordCard { number:  6, word: "Power",          dimension: "The capacity to act, to create, or to restrain" },
    OhWordCard { number:  7, word: "Shame",          dimension: "The belief that something at the core is defective" },
    OhWordCard { number:  8, word: "Tenderness",     dimension: "The soft quality of care offered without armour" },
    OhWordCard { number:  9, word: "Anger",          dimension: "The energy that arises when a boundary is crossed" },
    OhWordCard { number: 10, word: "Memory",         dimension: "The past as it lives in the present body" },
    OhWordCard { number: 11, word: "Play",           dimension: "Action without agenda; the intrinsically rewarding" },
    OhWordCard { number: 12, word: "Boundary",       dimension: "The line that defines where I end and another begins" },
    OhWordCard { number: 13, word: "Joy",            dimension: "The aliveness that arises when life is received fully" },
    OhWordCard { number: 14, word: "Loss",           dimension: "The space left by what was once present" },
    OhWordCard { number: 15, word: "Mother",         dimension: "The archetype of nurturance, origin, and first relationship" },
    OhWordCard { number: 16, word: "Father",         dimension: "The archetype of authority, structure, and initiation" },
    OhWordCard { number: 17, word: "Control",        dimension: "The attempt to manage uncertainty by managing circumstances" },
    OhWordCard { number: 18, word: "Vulnerability",  dimension: "The state of being open to being hurt, and choosing it anyway" },
    OhWordCard { number: 19, word: "Success",        dimension: "Reaching a goal; the question of whose definition of success" },
    OhWordCard { number: 20, word: "Failure",        dimension: "Not reaching a goal; the question of what was learned" },
    OhWordCard { number: 21, word: "Body",           dimension: "The physical self; the site of sensation, pleasure, and pain" },
    OhWordCard { number: 22, word: "Death",          dimension: "The ending of a form; the transformation that follows" },
    OhWordCard { number: 23, word: "Desire",         dimension: "The pull toward what would complete or satisfy" },
    OhWordCard { number: 24, word: "Secret",         dimension: "What is known but not spoken; what is hidden from others or from oneself" },
    OhWordCard { number: 25, word: "Freedom",        dimension: "The state of moving without constraint, chosen or unchosen" },
    OhWordCard { number: 26, word: "Forgiveness",    dimension: "The release of a claim against another or oneself" },
    OhWordCard { number: 27, word: "Belonging",      dimension: "The felt sense of being a valued part of a larger whole" },
    OhWordCard { number: 28, word: "Courage",        dimension: "Acting in the presence of fear, not in its absence" },
    OhWordCard { number: 29, word: "Hope",           dimension: "The orientation toward a future that could be better" },
    OhWordCard { number: 30, word: "Responsibility", dimension: "The ownership of one's actions and their consequences" },
    OhWordCard { number: 31, word: "Shadow",         dimension: "The aspects of the self not acknowledged or integrated" },
    OhWordCard { number: 32, word: "Destiny",        dimension: "The sense of a life shaped by forces larger than oneself" },
    OhWordCard { number: 33, word: "Creativity",     dimension: "The capacity to bring something new into being" },
    OhWordCard { number: 34, word: "Surrender",      dimension: "The release of control in the face of what cannot be controlled" },
    OhWordCard { number: 35, word: "Dignity",        dimension: "The intrinsic worth that cannot be given or taken by others" },
    OhWordCard { number: 36, word: "Intimacy",       dimension: "The state of being truly known and truly knowing another" },
    OhWordCard { number: 37, word: "Grief",          dimension: "The process of integrating a loss into a continuing life" },
    OhWordCard { number: 38, word: "Meaning",        dimension: "The sense that life and its events cohere toward something" },
    OhWordCard { number: 39, word: "Change",         dimension: "The movement from one state to another; transition" },
    OhWordCard { number: 40, word: "Patience",       dimension: "The capacity to wait without losing faith or peace" },
    OhWordCard { number: 41, word: "Identity",       dimension: "The answer to the question: who am I, really?" },
    OhWordCard { number: 42, word: "Acceptance",     dimension: "The recognition of what is, without demand that it be otherwise" },
    OhWordCard { number: 43, word: "Love",           dimension: "The will toward the flourishing of another" },
    OhWordCard { number: 44, word: "Becoming",       dimension: "The ongoing process of growing into what one most truly is" },
];

// ─── Lookup helpers ───────────────────────────────────────────────────────────

/// Find an OH image card by number (1–44).
pub fn oh_image_by_number(n: u8) -> Option<&'static OhImageCard> {
    OH_IMAGES.iter().find(|c| c.number == n)
}

/// Find an OH word card by number (1–44).
pub fn oh_word_by_number(n: u8) -> Option<&'static OhWordCard> {
    OH_WORDS.iter().find(|c| c.number == n)
}

/// Find an OH word card by word (case-insensitive, partial match).
#[allow(dead_code)]
pub fn oh_word_by_word(query: &str) -> Option<&'static OhWordCard> {
    let q = query.to_lowercase();
    OH_WORDS
        .iter()
        .find(|c| c.word.to_lowercase().contains(&q))
}
