//! Thoth Tarot — 56 Minor Arcana (40 pip + 16 court cards)
//!
//! Data sources:
//!   Crowley, A. (1944). *The Book of Thoth*. O.T.O.
//!   DuQuette, L.M. (2003). *Understanding Aleister Crowley's Thoth Tarot*. Weiser Books.
//!   Regardie, I. (1989). *The Golden Dawn* (6th ed.). Llewellyn.
//!
//! Sephiroth for pip numbers: Aces=Kether, 2s=Chokmah, 3s=Binah, 4s=Chesed,
//!   5s=Geburah, 6s=Tiphareth, 7s=Netzach, 8s=Hod, 9s=Yesod, 10s=Malkuth.
//!
//! Court card ranks in Thoth (diverging from RWS King/Queen/Knight/Page):
//!   Knight = mounted, fiery King-energy; Queen = watery; Prince = airy; Princess = earthy.
//!
//! Astrological decan system: each pip 2–10 covers one of the 36 decans
//! (10° of a zodiac sign), attributed per the Golden Dawn/Crowley method.

// ─── Struct ──────────────────────────────────────────────────────────────────

/// One Minor Arcanum of the Thoth Tarot.
#[derive(Debug)]
pub struct ThothMinor {
    /// Numeric rank: 1=Ace, 2–10=pip, 11=Knight, 12=Queen, 13=Prince, 14=Princess.
    pub number: u8,
    /// English rank name.
    pub rank_name: &'static str,
    /// Suit name.
    pub suit: &'static str,
    /// Distinctive Thoth title (Crowley's *Book of Thoth*).
    pub title: &'static str,
    /// Sephirah on the Tree of Life (empty string for court cards).
    pub sephirah: &'static str,
    /// Astrological decan or elemental attribution.
    pub astrology: &'static str,
    /// Elemental nature of the suit.
    pub element: &'static str,
    /// Divinatory meaning, upright / well-dignified.
    pub meaning: &'static str,
    /// Divinatory meaning, reversed / ill-dignified.
    pub reversed: &'static str,
}

// ─── Card data ───────────────────────────────────────────────────────────────
//
// Order: Wands (1–14), Cups (1–14), Swords (1–14), Disks (1–14).

pub static THOTH_MINOR: [ThothMinor; 56] = [

    // ════════════════════════════════════════════════════════════════════════
    // WANDS
    // ════════════════════════════════════════════════════════════════════════

    ThothMinor {
        number: 1,
        rank_name: "Ace",
        suit: "Wands",
        title: "Root of Fire",
        sephirah: "Kether",
        astrology: "Primal Fire",
        element: "Fire",
        meaning: "Pure creative will igniting; the unmanifest spark of Hadit; raw Yod-force at its source",
        reversed: "False starts, will without direction, creative energy dissipated before it can take form",
    },
    ThothMinor {
        number: 2,
        rank_name: "Two",
        suit: "Wands",
        title: "Dominion",
        sephirah: "Chokmah",
        astrology: "Mars in Aries",
        element: "Fire",
        meaning: "Bold assertion of will, confident leadership; Mars in Aries gives fearless dominion over self",
        reversed: "Domineering or timid, failure of nerve at the threshold; will without direction collapses",
    },
    ThothMinor {
        number: 3,
        rank_name: "Three",
        suit: "Wands",
        title: "Virtue",
        sephirah: "Binah",
        astrology: "Sun in Aries",
        element: "Fire",
        meaning: "Established strength of character; solar virtue illuminating the path; creative enterprise launched",
        reversed: "Arrogance masking weakness, vanity without substance, creative projects stalled by pride",
    },
    ThothMinor {
        number: 4,
        rank_name: "Four",
        suit: "Wands",
        title: "Completion",
        sephirah: "Chesed",
        astrology: "Venus in Aries",
        element: "Fire",
        meaning: "Settlement, joyful completion; Venus harmonises Aries fire into a stable and beautiful result",
        reversed: "Celebration premature, unstable foundations, creative project incomplete beneath surface success",
    },
    ThothMinor {
        number: 5,
        rank_name: "Five",
        suit: "Wands",
        title: "Strife",
        sephirah: "Geburah",
        astrology: "Saturn in Leo",
        element: "Fire",
        meaning: "Necessary conflict tempering will; struggle that, if accepted, forges stronger character",
        reversed: "Pointless quarrelling, violence for its own sake, energy wasted in unproductive competition",
    },
    ThothMinor {
        number: 6,
        rank_name: "Six",
        suit: "Wands",
        title: "Victory",
        sephirah: "Tiphareth",
        astrology: "Jupiter in Leo",
        element: "Fire",
        meaning: "Hard-won triumph; Jupiter magnifies Leo's solar will into public recognition and success",
        reversed: "Pride after the fall, hollow victory, gain that breeds complacency and eventual defeat",
    },
    ThothMinor {
        number: 7,
        rank_name: "Seven",
        suit: "Wands",
        title: "Valour",
        sephirah: "Netzach",
        astrology: "Mars in Leo",
        element: "Fire",
        meaning: "Courage under pressure; holding ground against odds through sheer force of will and heart",
        reversed: "Cowardice, inability to defend one's position, aggression without discipline or inner conviction",
    },
    ThothMinor {
        number: 8,
        rank_name: "Eight",
        suit: "Wands",
        title: "Swiftness",
        sephirah: "Hod",
        astrology: "Mercury in Sagittarius",
        element: "Fire",
        meaning: "Rapid movement, swift communication; ideas and projects accelerate to culmination without delay",
        reversed: "Haste causing errors, communication too fast to be understood, impulsive action misfires",
    },
    ThothMinor {
        number: 9,
        rank_name: "Nine",
        suit: "Wands",
        title: "Strength",
        sephirah: "Yesod",
        astrology: "Moon in Sagittarius",
        element: "Fire",
        meaning: "Tremendous accumulated force held in reserve; strength of moon-tides channelled into endurance",
        reversed: "Obstinacy, force without wisdom, defensive posture that prevents growth and new connection",
    },
    ThothMinor {
        number: 10,
        rank_name: "Ten",
        suit: "Wands",
        title: "Oppression",
        sephirah: "Malkuth",
        astrology: "Saturn in Sagittarius",
        element: "Fire",
        meaning: "Will burdened to breaking; Saturn constrains Sagittarius fire; a warning to relinquish excess",
        reversed: "Catastrophic burnout, cruel wielding of power, burdens self-imposed through refusal to delegate",
    },
    ThothMinor {
        number: 11,
        rank_name: "Knight",
        suit: "Wands",
        title: "Knight of Wands",
        sephirah: "",
        astrology: "21° Scorpio – 20° Sagittarius",
        element: "Fire of Fire",
        meaning: "Fiery, swift, magnetic leader; passionate and generous but prone to impulsive decisions",
        reversed: "Rash, cruel, intolerant; a brilliant spark that burns out or scorches those around it",
    },
    ThothMinor {
        number: 12,
        rank_name: "Queen",
        suit: "Wands",
        title: "Queen of Wands",
        sephirah: "",
        astrology: "21° Pisces – 20° Aries",
        element: "Water of Fire",
        meaning: "Fierce, creative, fiercely independent woman of great personal magnetism and warm generosity",
        reversed: "Domineering, sly, jealous; power used to control rather than inspire; pride turned cruel",
    },
    ThothMinor {
        number: 13,
        rank_name: "Prince",
        suit: "Wands",
        title: "Prince of Wands",
        sephirah: "",
        astrology: "21° Cancer – 20° Leo",
        element: "Air of Fire",
        meaning: "Swift, daring, noble-hearted; ideas rapidly executed; the airy refinement of fire's pure will",
        reversed: "Intolerant, prejudiced, volatile; brilliance eclipsed by cruel impatience and self-importance",
    },
    ThothMinor {
        number: 14,
        rank_name: "Princess",
        suit: "Wands",
        title: "Princess of Wands",
        sephirah: "",
        astrology: "Earth of Fire · Ruler of Aries–Taurus–Gemini quadrant",
        element: "Earth of Fire",
        meaning: "Brilliant, bold newcomer; raw creative potential; the earthing of fire into enthusiastic action",
        reversed: "Superficiality, vanity, cruelty, and instability; potential consumed in drama rather than deed",
    },

    // ════════════════════════════════════════════════════════════════════════
    // CUPS
    // ════════════════════════════════════════════════════════════════════════

    ThothMinor {
        number: 1,
        rank_name: "Ace",
        suit: "Cups",
        title: "Root of Water",
        sephirah: "Kether",
        astrology: "Primal Water",
        element: "Water",
        meaning: "Pure receptive love; the Grail overflowing; Binah's womb before form; infinite compassion",
        reversed: "Emotional emptiness, love offered but rejected, the cup overturned and its grace wasted",
    },
    ThothMinor {
        number: 2,
        rank_name: "Two",
        suit: "Cups",
        title: "Love",
        sephirah: "Chokmah",
        astrology: "Venus in Cancer",
        element: "Water",
        meaning: "Harmonious union, mutual understanding; Venus in Cancer brings tender, fertile, lasting love",
        reversed: "Co-dependence, love soured by possession, attraction without deeper compatibility or respect",
    },
    ThothMinor {
        number: 3,
        rank_name: "Three",
        suit: "Cups",
        title: "Abundance",
        sephirah: "Binah",
        astrology: "Mercury in Cancer",
        element: "Water",
        meaning: "Joyful celebration, communal richness; Mercury in Cancer quickens emotional bonds into bounty",
        reversed: "Excess, superficial pleasure, overindulgence that empties the cup of genuine nourishment",
    },
    ThothMinor {
        number: 4,
        rank_name: "Four",
        suit: "Cups",
        title: "Luxury",
        sephirah: "Chesed",
        astrology: "Moon in Cancer",
        element: "Water",
        meaning: "Sensuous pleasure approaching surfeit; bliss that carries the seed of its own dissolution",
        reversed: "Disgust, emotional stagnation, clinging to pleasures that have turned hollow and corrosive",
    },
    ThothMinor {
        number: 5,
        rank_name: "Five",
        suit: "Cups",
        title: "Disappointment",
        sephirah: "Geburah",
        astrology: "Mars in Scorpio",
        element: "Water",
        meaning: "Emotional loss cutting to the truth; Mars in Scorpio dismantles illusions for deeper wisdom",
        reversed: "Chronic sorrow, emotional masochism, wallowing in grief beyond its instructive purpose",
    },
    ThothMinor {
        number: 6,
        rank_name: "Six",
        suit: "Cups",
        title: "Pleasure",
        sephirah: "Tiphareth",
        astrology: "Sun in Scorpio",
        element: "Water",
        meaning: "Warm, harmonious delight; solar beauty illuminating emotional depth; joy rooted in truth",
        reversed: "Nostalgia as avoidance, pleasure tainted by past regret, inability to enjoy the present",
    },
    ThothMinor {
        number: 7,
        rank_name: "Seven",
        suit: "Cups",
        title: "Debauch",
        sephirah: "Netzach",
        astrology: "Venus in Scorpio",
        element: "Water",
        meaning: "Venus in Scorpio poisons beauty; illusion, addiction, the cup filled with seductive unreality",
        reversed: "Waking from delusion too late, intoxication destroying relationships and creative purpose",
    },
    ThothMinor {
        number: 8,
        rank_name: "Eight",
        suit: "Cups",
        title: "Indolence",
        sephirah: "Hod",
        astrology: "Saturn in Pisces",
        element: "Water",
        meaning: "Purposeless drifting; Saturn weighs on Pisces dreaminess to produce creative paralysis",
        reversed: "Depression, abandonment of endeavour, emotional withdrawal that has become self-defeating",
    },
    ThothMinor {
        number: 9,
        rank_name: "Nine",
        suit: "Cups",
        title: "Happiness",
        sephirah: "Yesod",
        astrology: "Jupiter in Pisces",
        element: "Water",
        meaning: "Emotional fulfilment, the wish granted; Jupiter in Pisces expands compassion into true joy",
        reversed: "Smugness, satisfaction that closes one off from growth, happiness hoarded rather than shared",
    },
    ThothMinor {
        number: 10,
        rank_name: "Ten",
        suit: "Cups",
        title: "Satiety",
        sephirah: "Malkuth",
        astrology: "Mars in Pisces",
        element: "Water",
        meaning: "Fullness that has tipped into excess; Mars in Pisces drives emotion to its final bitter surfeit",
        reversed: "Emotional gluttony, disgust at abundance, the heart so gorged it can no longer receive love",
    },
    ThothMinor {
        number: 11,
        rank_name: "Knight",
        suit: "Cups",
        title: "Knight of Cups",
        sephirah: "",
        astrology: "21° Aquarius – 20° Pisces",
        element: "Fire of Water",
        meaning: "Graceful, romantic, visionary; a poet-warrior whose fierce feeling inspires and ennobles others",
        reversed: "Idle dreamer, seducer, emotional volatility, charm concealing manipulation or self-deception",
    },
    ThothMinor {
        number: 12,
        rank_name: "Queen",
        suit: "Cups",
        title: "Queen of Cups",
        sephirah: "",
        astrology: "21° Gemini – 20° Cancer",
        element: "Water of Water",
        meaning: "Pure intuition, loving wisdom, psychic sensitivity; the mirror of the soul's deep waters",
        reversed: "Psychic confusion, emotional manipulation, the reflective surface turned to distortion",
    },
    ThothMinor {
        number: 13,
        rank_name: "Prince",
        suit: "Cups",
        title: "Prince of Cups",
        sephirah: "",
        astrology: "21° Libra – 20° Scorpio",
        element: "Air of Water",
        meaning: "Subtle, artistic, deeply feeling; ideas born from emotion; the creative intellect of the heart",
        reversed: "Deceptive charm, emotional detachment masked as intellect, manipulation through illusion",
    },
    ThothMinor {
        number: 14,
        rank_name: "Princess",
        suit: "Cups",
        title: "Princess of Cups",
        sephirah: "",
        astrology: "Earth of Water · Ruler of Cancer–Leo–Virgo quadrant",
        element: "Earth of Water",
        meaning: "Gentle, dreamy, loving; imagination made concrete; the creative feeling brought into daily life",
        reversed: "Impractical fantasist, emotional dependency, seductive unreliability, gifts dissipated in daydream",
    },

    // ════════════════════════════════════════════════════════════════════════
    // SWORDS
    // ════════════════════════════════════════════════════════════════════════

    ThothMinor {
        number: 1,
        rank_name: "Ace",
        suit: "Swords",
        title: "Root of Air",
        sephirah: "Kether",
        astrology: "Primal Air",
        element: "Air",
        meaning: "Pure mind, the sword of truth; Kether's will expressed as absolute intellectual clarity",
        reversed: "Tyranny of the mind, truth wielded destructively, the intellect severing feeling from wisdom",
    },
    ThothMinor {
        number: 2,
        rank_name: "Two",
        suit: "Swords",
        title: "Peace",
        sephirah: "Chokmah",
        astrology: "Moon in Libra",
        element: "Air",
        meaning: "Temporary truce; the mind stilled to observe; Moon in Libra restores balance after conflict",
        reversed: "Indecision masking anxiety, false peace that avoids necessary confrontation, standoff unresolved",
    },
    ThothMinor {
        number: 3,
        rank_name: "Three",
        suit: "Swords",
        title: "Sorrow",
        sephirah: "Binah",
        astrology: "Saturn in Libra",
        element: "Air",
        meaning: "Grief as teacher; Saturn's reality-weight in Libra cuts illusion to reveal what truly matters",
        reversed: "Chronic sorrow weaponised, mental suffering without growth, painful truths refused",
    },
    ThothMinor {
        number: 4,
        rank_name: "Four",
        suit: "Swords",
        title: "Truce",
        sephirah: "Chesed",
        astrology: "Jupiter in Libra",
        element: "Air",
        meaning: "Enforced rest, strategic withdrawal; Jupiter in Libra negotiates the cessation of mental conflict",
        reversed: "Stagnation disguised as peace, avoidance of necessary action, retreat become permanent escape",
    },
    ThothMinor {
        number: 5,
        rank_name: "Five",
        suit: "Swords",
        title: "Defeat",
        sephirah: "Geburah",
        astrology: "Venus in Aquarius",
        element: "Air",
        meaning: "Intellectual or moral defeat; the mind overcome; accepting loss as the beginning of recovery",
        reversed: "Shameful surrender, cowardice, defeat accepted without learning, or catastrophic loss of nerve",
    },
    ThothMinor {
        number: 6,
        rank_name: "Six",
        suit: "Swords",
        title: "Science",
        sephirah: "Tiphareth",
        astrology: "Mercury in Aquarius",
        element: "Air",
        meaning: "The triumph of mind over emotion; rational mastery, earned success through methodical thought",
        reversed: "Cold logic without compassion, scientism as ideology, intellect cutting off the heart entirely",
    },
    ThothMinor {
        number: 7,
        rank_name: "Seven",
        suit: "Swords",
        title: "Futility",
        sephirah: "Netzach",
        astrology: "Moon in Aquarius",
        element: "Air",
        meaning: "Mental effort producing no result; Moon in Aquarius scatters Netzach's desire into abstraction",
        reversed: "Cunning without purpose, theft of ideas, plans that self-sabotage through indirection",
    },
    ThothMinor {
        number: 8,
        rank_name: "Eight",
        suit: "Swords",
        title: "Interference",
        sephirah: "Hod",
        astrology: "Jupiter in Gemini",
        element: "Air",
        meaning: "Obstruction, too many ideas; Jupiter in Gemini expands mental chatter until clarity is lost",
        reversed: "Paralysis by analysis, self-censorship, other people's agendas blocking clear thought",
    },
    ThothMinor {
        number: 9,
        rank_name: "Nine",
        suit: "Swords",
        title: "Cruelty",
        sephirah: "Yesod",
        astrology: "Mars in Gemini",
        element: "Air",
        meaning: "The mind turned against itself or others; Mars in Gemini weaponises intellect into cruelty",
        reversed: "Despair, malice, nightmares made real; the relentless inner critic at its most destructive",
    },
    ThothMinor {
        number: 10,
        rank_name: "Ten",
        suit: "Swords",
        title: "Ruin",
        sephirah: "Malkuth",
        astrology: "Sun in Gemini",
        element: "Air",
        meaning: "Total intellectual collapse; the Sun illuminates how completely the mind has destroyed itself",
        reversed: "Utter defeat treated as liberation; the phoenix moment after everything has been demolished",
    },
    ThothMinor {
        number: 11,
        rank_name: "Knight",
        suit: "Swords",
        title: "Knight of Swords",
        sephirah: "",
        astrology: "21° Taurus – 20° Gemini",
        element: "Fire of Air",
        meaning: "Fierce, incisive, brilliant warrior of the mind; cuts to truth with fearless conviction",
        reversed: "Tyrannical, fanatical, brutal; a razor intelligence divorced from empathy or consequences",
    },
    ThothMinor {
        number: 12,
        rank_name: "Queen",
        suit: "Swords",
        title: "Queen of Swords",
        sephirah: "",
        astrology: "21° Virgo – 20° Libra",
        element: "Water of Air",
        meaning: "Perceptive, swift, and keenly intelligent; sorrow sharpened into unsparing but just discernment",
        reversed: "Cruel wit, bitter isolation, grief weaponised, the mind cutting away all warmth and connection",
    },
    ThothMinor {
        number: 13,
        rank_name: "Prince",
        suit: "Swords",
        title: "Prince of Swords",
        sephirah: "",
        astrology: "21° Capricorn – 20° Aquarius",
        element: "Air of Air",
        meaning: "Pure intellect in motion; idealistic, innovative, full of ideas but requires grounding in will",
        reversed: "Scatter-brained, deceitful, ideas multiplied without completion; intellect devouring itself",
    },
    ThothMinor {
        number: 14,
        rank_name: "Princess",
        suit: "Swords",
        title: "Princess of Swords",
        sephirah: "",
        astrology: "Earth of Air · Ruler of Capricorn–Aquarius–Pisces quadrant",
        element: "Earth of Air",
        meaning: "Keen, clever, observant; brings ideas into practical form; watchfulness concealing sharp will",
        reversed: "Spiteful gossip, shallow cunning, ideas without constructive application, cruelty as defence",
    },

    // ════════════════════════════════════════════════════════════════════════
    // DISKS
    // ════════════════════════════════════════════════════════════════════════

    ThothMinor {
        number: 1,
        rank_name: "Ace",
        suit: "Disks",
        title: "Root of Earth",
        sephirah: "Kether",
        astrology: "Primal Earth",
        element: "Earth",
        meaning: "Infinite material potential at its source; Kether expressing through Assiah; the seed of worlds",
        reversed: "Greed, inertia, potential blocked from materialising; wealth hoarded rather than cultivated",
    },
    ThothMinor {
        number: 2,
        rank_name: "Two",
        suit: "Disks",
        title: "Change",
        sephirah: "Chokmah",
        astrology: "Jupiter in Capricorn",
        element: "Earth",
        meaning: "Harmonious change, juggling resources; Jupiter moderates Saturn's rigidity to allow adaptation",
        reversed: "Imbalance, financial instability, inability to manage change; spinning too many plates at once",
    },
    ThothMinor {
        number: 3,
        rank_name: "Three",
        suit: "Disks",
        title: "Works",
        sephirah: "Binah",
        astrology: "Mars in Capricorn",
        element: "Earth",
        meaning: "Skilled labour bearing fruit; Mars in Capricorn drives disciplined effort into lasting structure",
        reversed: "Shoddy work, effort not rewarded, labour in service of the wrong master or wrong goal",
    },
    ThothMinor {
        number: 4,
        rank_name: "Four",
        suit: "Disks",
        title: "Power",
        sephirah: "Chesed",
        astrology: "Sun in Capricorn",
        element: "Earth",
        meaning: "Solidified material power; Chesed's generosity structured by Capricorn into enduring fortress",
        reversed: "Miserliness, hoarding power against all comers, authority calcified into obstruction",
    },
    ThothMinor {
        number: 5,
        rank_name: "Five",
        suit: "Disks",
        title: "Worry",
        sephirah: "Geburah",
        astrology: "Mercury in Taurus",
        element: "Earth",
        meaning: "Anxiety about material security; Mercury's restlessness undermining Taurus's natural steadiness",
        reversed: "Chronic financial anxiety, rumination destroying productivity, scarcity mindset entrenched",
    },
    ThothMinor {
        number: 6,
        rank_name: "Six",
        suit: "Disks",
        title: "Success",
        sephirah: "Tiphareth",
        astrology: "Moon in Taurus",
        element: "Earth",
        meaning: "Earned material success; Moon exalted in Taurus brings fertile prosperity and generous reward",
        reversed: "Success not shared, beneficence withheld, reward conditional on submission to the giver",
    },
    ThothMinor {
        number: 7,
        rank_name: "Seven",
        suit: "Disks",
        title: "Failure",
        sephirah: "Netzach",
        astrology: "Saturn in Taurus",
        element: "Earth",
        meaning: "Investment without return; Saturn's burden crushes Taurus's growth before it can materialise",
        reversed: "Persistent loss, fruitless labour, inability to learn from repeated material failure",
    },
    ThothMinor {
        number: 8,
        rank_name: "Eight",
        suit: "Disks",
        title: "Prudence",
        sephirah: "Hod",
        astrology: "Sun in Virgo",
        element: "Earth",
        meaning: "Careful mastery of craft; the Sun in Virgo illumines meticulous work yielding steady reward",
        reversed: "Over-caution, miserly hoarding of skill, prudence tipping into paralysing perfectionism",
    },
    ThothMinor {
        number: 9,
        rank_name: "Nine",
        suit: "Disks",
        title: "Gain",
        sephirah: "Yesod",
        astrology: "Venus in Virgo",
        element: "Earth",
        meaning: "Material gain through refined skill; Venus in Virgo brings beauty and love to practical mastery",
        reversed: "Ill-gotten gains, material comfort divorced from integrity, abundance without fulfilment",
    },
    ThothMinor {
        number: 10,
        rank_name: "Ten",
        suit: "Disks",
        title: "Wealth",
        sephirah: "Malkuth",
        astrology: "Mercury in Virgo",
        element: "Earth",
        meaning: "Material completion; the Great Work of Malkuth; riches of body, skill, and legacy fully realised",
        reversed: "Excessive accumulation, inheritance as burden, wealth hoarded until it stifles all living growth",
    },
    ThothMinor {
        number: 11,
        rank_name: "Knight",
        suit: "Disks",
        title: "Knight of Disks",
        sephirah: "",
        astrology: "21° Leo – 20° Virgo",
        element: "Fire of Earth",
        meaning: "Methodical, patient, reliable; the fiery will grounded into practical, sustained material effort",
        reversed: "Dull, plodding, avaricious; endurance without vision; stubbornness blocking necessary change",
    },
    ThothMinor {
        number: 12,
        rank_name: "Queen",
        suit: "Disks",
        title: "Queen of Disks",
        sephirah: "",
        astrology: "21° Sagittarius – 20° Capricorn",
        element: "Water of Earth",
        meaning: "Practical nurture, material generosity; the great mother tending body, home, and earth with love",
        reversed: "Neglect of domestic life, materialism without warmth, nurture withheld as control",
    },
    ThothMinor {
        number: 13,
        rank_name: "Prince",
        suit: "Disks",
        title: "Prince of Disks",
        sephirah: "",
        astrology: "21° Aries – 20° Taurus",
        element: "Air of Earth",
        meaning: "Industrious, patient, ingenious; the thinking applied to matter; ideas that build lasting things",
        reversed: "Stubborn, complacent, over-materialistic; intellect trapped in routine without higher aspiration",
    },
    ThothMinor {
        number: 14,
        rank_name: "Princess",
        suit: "Disks",
        title: "Princess of Disks",
        sephirah: "",
        astrology: "Earth of Earth · Ruler of Libra–Scorpio–Sagittarius quadrant",
        element: "Earth of Earth",
        meaning: "Fertile new beginning in material life; earthy, strong, patient; the seed ripening underground",
        reversed: "Inertia, wastefulness, potential hoarded in comfort rather than cultivated into growth",
    },
];

// ─── Lookup functions ─────────────────────────────────────────────────────────

/// Return all cards belonging to a given suit (case-insensitive).
pub fn thoth_suit_cards(suit: &str) -> Vec<&'static ThothMinor> {
    let s = suit.to_lowercase();
    THOTH_MINOR
        .iter()
        .filter(|c| c.suit.to_lowercase() == s)
        .collect()
}

/// Return a specific card by suit and rank name — both case-insensitive exact match.
///
/// `rank` may be a number word ("Ace", "Two" … "Ten") or court name
/// ("Knight", "Queen", "Prince", "Princess").
pub fn thoth_minor_by_suit_rank(suit: &str, rank: &str) -> Option<&'static ThothMinor> {
    let s = suit.to_lowercase();
    let r = rank.to_lowercase();
    THOTH_MINOR
        .iter()
        .find(|c| c.suit.to_lowercase() == s && c.rank_name.to_lowercase() == r)
}
