#!/usr/bin/env python3
"""
gen_verses_rs.py — Generate src/bible/verses_data.rs from the populated
cosmic_knowledge.db, embedding all KJV verses as a Rust static slice.

Usage (from project root):
    python data/gen_verses_rs.py data/cosmic_knowledge.db src/bible/verses_data.rs
"""

import sqlite3
import sys
import os

def escape_rust_str(s):
    """Escape a string for use inside a Rust double-quoted string literal."""
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    return s

def generate(db_path, out_path):
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    cur.execute("SELECT book, chapter, verse, text FROM verses ORDER BY id")
    rows = cur.fetchall()
    conn.close()

    print(f"  Loaded {len(rows):,} verses from {db_path}")

    lines = []
    lines.append("//! KJV Bible verses — auto-generated by data/gen_verses_rs.py")
    lines.append("//! DO NOT EDIT BY HAND.")
    lines.append("//!")
    lines.append("//! Source: King James Version, Project Gutenberg EBook #10 (public domain).")
    lines.append("")
    lines.append("/// All 66 books · 30 374 verses of the King James Version.")
    lines.append("/// Tuple layout: (book, chapter, verse, text).")
    lines.append("pub static KJV_VERSES: &[(&str, u32, u32, &str)] = &[")

    for book, chapter, verse, text in rows:
        escaped = escape_rust_str(text)
        lines.append(f'    ("{escape_rust_str(book)}", {chapter}, {verse}, "{escaped}"),')

    lines.append("];")
    lines.append("")

    content = "\n".join(lines)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    size_kb = os.path.getsize(out_path) // 1024
    print(f"  Written {out_path}  ({size_kb} KB, {len(rows):,} entries)")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python gen_verses_rs.py <cosmic_knowledge.db> <out.rs>")
        sys.exit(1)
    generate(sys.argv[1], sys.argv[2])
    print("Done.")
