#!/usr/bin/env python3
"""
gen_quran_rs.py — Generate src/quran/verses_data.rs from the populated
cosmic_knowledge.db, embedding all Quran ayahs as a Rust static slice.

Usage (from project root):
    python data/gen_quran_rs.py data/cosmic_knowledge.db src/quran/verses_data.rs
"""

import sqlite3
import sys
import os

def escape_rust_str(s):
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    return s

def generate(db_path, out_path):
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    cur.execute("SELECT surah, ayah, surah_name, text FROM quran_verses ORDER BY id")
    rows = cur.fetchall()
    conn.close()

    print(f"  Loaded {len(rows):,} ayahs from {db_path}")

    lines = []
    lines.append("//! Quran ayahs — auto-generated by data/gen_quran_rs.py")
    lines.append("//! DO NOT EDIT BY HAND.")
    lines.append("//!")
    lines.append("//! Translation: Marmaduke William Pickthall (1930), public domain.")
    lines.append("//! Source: Project Gutenberg EBook #16955.")
    lines.append("")
    lines.append("/// All 114 surahs of the Quran (Pickthall English translation).")
    lines.append("/// Tuple layout: (surah, ayah, surah_name, text).")
    lines.append("pub static QURAN_VERSES: &[(u32, u32, &str, &str)] = &[")

    for surah, ayah, surah_name, text in rows:
        lines.append(
            f'    ({surah}, {ayah}, "{escape_rust_str(surah_name)}", "{escape_rust_str(text)}"),'
        )

    lines.append("];")
    lines.append("")

    content = "\n".join(lines)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    size_kb = os.path.getsize(out_path) // 1024
    print(f"  Written {out_path}  ({size_kb} KB, {len(rows):,} entries)")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python gen_quran_rs.py <cosmic_knowledge.db> <out.rs>")
        sys.exit(1)
    generate(sys.argv[1], sys.argv[2])
    print("Done.")
